Proyecto_RadixWeb/Models/asistencias.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencias
    {
        public int asis_id { get; set; }
        public Nullable<int> Con_Id { get; set; }
        public Nullable<int> Hl_Id { get; set; }
        public Nullable<bool> asis_estado { get; set; }
    
        public virtual contratos contratos { get; set; }
        public virtual horario_laboral horario_laboral { get; set; }
    }
}

Proyecto_RadixWeb/Controllers/AsistenciasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_RadixWeb.Models;

namespace Proyecto_RadixWeb.Controllers
{
    public class AsistenciasController : Controller
    {
        private radixEntities db = new radixEntities();

        // GET: Asistencias
        public ActionResult Index(int? subemp_id, int? car_id)
        {
            var subempcar = db.subempresa_cargo.FirstOrDefault(s => s.Sub_Id == subemp_id && s.Car_Id == car_id);

            var asistencias = db.asistencias.Include(a => a.contratos).Include(a => a.horario_laboral);
            return View(asistencias.Where(a => a.horario_laboral.Subempcar_id == subempcar.Subempcar_id).ToList());
        }

        public ActionResult Asistencia_Personas(int? Subempcar_id, int? horario_id)
        {
            ViewBag.empresa = HttpContext.Session["Empresa"].ToString();

            var subempcar = db.subempresa_cargo.FirstOrDefault(s => s.Subempcar_id == Subempcar_id);


            ViewBag.car_id = subempcar.Car_Id;
            ViewBag.subemp_id = subempcar.Sub_Id;

            ViewBag.Subempcar_id = Subempcar_id;
            ViewBag.horario_id = horario_id;

            var contratos = db.contratos.Include(c => c.personas).Include(c => c.subempresas);
            var asistencias = db.asistencias.Include(a => a.contratos).Include(a => a.horario_laboral);

            ViewBag.contar = db.asistencias.Count(a => a.Hl_Id == horario_id);

            MultiplesClases multiple = new MultiplesClases
            {

                ObjEContrato = contratos.Where(c => c.Sub_Id == subempcar.Sub_Id && c.personas.Car_Id == subempcar.Car_Id).ToList(),
                ObjEAsistencia = asistencias.Where(a => a.Hl_Id == horario_id).ToList()

            };


            return View(multiple);
        }

        [HttpPost]
        public JsonResult Guardar_Asistencia(List<asistencias> lista_asistencia)
        {
            var status = false;

            if (lista_asistencia == null)
            {
                lista_asistencia = new List<asistencias>();
            }
            

            foreach (asistencias item in lista_asistencia)
            {
                if (item.asis_id > 0)
                {
                    var a = db.asistencias.Where(s => s.asis_id == item.asis_id).FirstOrDefault();

                    if (a != null)
                    {
                   
                        a.Con_Id = item.Con_Id;
                        a.Hl_Id = item.Hl_Id;
                        a.asis_estado = item.asis_estado;

                       
                    }

                }
                else
                {
                    db.asistencias.Add(item);

                }

                db.SaveChanges();
                status = true;



            }

            return new JsonResult { Data = new { status } };
        }


        // GET: Asistencias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            asistencias asistencias = db.asistencias.Find(id);
            if (asistencias == null)
            {
                return HttpNotFound();
            }
            return View(asistencias);
        }

        // GET: Asistencias/Create
        public ActionResult Create()
        {
            ViewBag.Con_Id = new SelectList(db.contratos, "Con_Id", "Per_Rut");
            ViewBag.Hl_Id = new SelectList(db.horario_laboral, "Hl_Id", "Hl_Titulo");
            return View();
        }

        // POST: Asistencias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "asis_id,Con_Id,Hl_Id,asis_estado")] asistencias asistencias)
        {
            if (ModelState.IsValid)
            {
                db.asistencias.Add(asistencias);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Con_Id = new SelectList(db.contratos, "Con_Id", "Per_Rut", asistencias.Con_Id);
            ViewBag.Hl_Id = new SelectList(db.horario_laboral, "Hl_Id", "Hl_Titulo", asistencias.Hl_Id);
            return View(asistencias);
        }

        // GET: Asistencias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            asistencias asistencias = db.asistencias.Find(id);
            if (asistencias == null)
            {
                return HttpNotFound();
            }
            ViewBag.Con_Id = new SelectList(db.contratos, "Con_Id", "Per_Rut", asistencias.Con_Id);
            ViewBag.Hl_Id = new SelectList(db.horario_laboral, "Hl_Id", "Hl_Titulo", asistencias.Hl_Id);
            return View(asistencias);
        }

        // POST: Asistencias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "asis_id,Con_Id,Hl_Id,asis_estado")] asistencias asistencias)
        {
            if (ModelState.IsValid)
            {
                db.Entry(asistencias).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Con_Id = new SelectList(db.contratos, "Con_Id", "Per_Rut", asistencias.Con_Id);
            ViewBag.Hl_Id = new SelectList(db.horario_laboral, "Hl_Id", "Hl_Titulo", asistencias.Hl_Id);
            return View(asistencias);
        }

        // GET: Asistencias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            asistencias asistencias = db.asistencias.Find(id);
            if (asistencias == null)
            {
                return HttpNotFound();
            }
            return View(asistencias);
        }

        // POST: Asistencias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            asistencias asistencias = db.asistencias.Find(id);
            db.asistencias.Remove(asistencias);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto_RadixWeb/Views/Asistencias/Asistencia_Personas.cshtml
@model Proyecto_RadixWeb.Models.MultiplesClases

@{
    ViewBag.Title = "Asistencia_Personas";
}

<div id="contenido_vista" style="margin-top: 90px; margin-left: 50px;">
    <div class="card mb-3 mt-2">
           <div class="card-body">
            <div class="table-responsive">


                <h2>Medir Asistencia Personas</h2>

                <h2><button id="btn_medir" class="btn btn-outline-success btn-sm m-0"> Aplicar </button></h2>



                <table class="table" id="tb_asistencia">

                    <thead>
                        <tr>

                            <th>
                                R.U.T
                            </th>
                            <th>
                                Nombre
                            </th>
                            <th>
                                Apellidos
                            </th>

                            <th></th>
                        </tr>
                    </thead>
                    @if (ViewBag.contar == 0)
                    {
                        <tbody>
                            @foreach (var item in Model.ObjEContrato)
                            {

                                <tr>
                                    <td style="display:none;">

                                        @Html.Hidden("item_asis_id", 0)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.personas.Per_Rut)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.personas.Per_Nom)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.personas.Per_ApePat)
                                        @Html.DisplayFor(modelItem => item.personas.Per_ApeMat)
                                    </td>
                                    <td>

                                     
                                        <label class="switch">
                                            <input type="checkbox" id="checkbox" value="@item.Con_Id" />
                                            <span class="slider round"></span>
                                        </label>
                                    </td>
                                </tr>

                            }
                        </tbody>


                    }
                    else if (ViewBag.contar > 0)
                    {
                        <tbody>
                            @foreach (var item in Model.ObjEAsistencia)
                            {

                                <tr>
                                    <td style="display:none;">
                                        @Html.HiddenFor(modelItem => item.asis_id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.contratos.personas.Per_Rut)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.contratos.personas.Per_Nom)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.contratos.personas.Per_ApePat)
                                        @Html.DisplayFor(modelItem => item.contratos.personas.Per_ApeMat)
                                    </td>
                                    <td>

                                        <label class="switch">
                                            @if (item.asis_estado == false)
                                            {
                                                <input type="checkbox" id="checkbox" value="@item.Con_Id" />

                                            }
                                            else if (item.asis_estado == true)
                                            {
                                                <input type="checkbox" id="checkbox" value="@item.Con_Id" checked/>

                                            }
                                            <span class="slider round"></span>
                                        </label>


                                    </td>
                                </tr>

                            }
                        </tbody>

                    }
                </table>
            </div>
        </div>

    </div>
</div>

<link href="~/Content/css/dashboard/app.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script>

    $(document).ready(function () {

        $('#contenido_vista').appendTo('#contenido_general');

    $('#btn_medir').on('click', function () {

        var lista_asistencia = [];

        //var filas = $('#tb_asistencia tbody tr').length;


        $('#tb_asistencia tbody tr').each(function ( ) {
            var horario_id = "@ViewBag.horario_id";

            var lista = {};

            var switchStatus = '';

            var rows = $('#tb_asistencia tbody tr').length;

               for (var i = 0; i < rows; i++) {
                   var row = $(this);


                   if (row.find("TD #checkbox").is(':checked')) {

                       switchStatus = row.find("td #checkbox").is(':checked');
                   }
                   else {
                       switchStatus = row.find("td #checkbox").is(':checked');
                   }


                   lista.asis_id = row.find("td #item_asis_id").val();

                   lista.Con_Id = row.find("td #checkbox").val();
                   lista.Hl_Id = horario_id;
                   lista.asis_estado = "" + switchStatus + "";


               }

            lista_asistencia.push(lista);

         });


         $.ajax({
                type: "POST",
                url: "@Url.Action("Guardar_Asistencia", "Asistencias")",
                data: {'lista_asistencia': lista_asistencia },
                success: function (data) {
                    if (data.status) {

                        window.location.href = "@Url.Action("Index", "Horario_laboral", new { Subempcar_id = ViewBag.Subempcar_id })";
                    }
                    alert('Almacenado');
                },
                error: function () {
                    alert('Error');
                }

            });
    });

    });

</script>
<style>
    .switch {
        display: inline-block;
        height: 34px;
        position: relative;
        width: 60px;
    }

        .switch input {
            display: none;
        }

    .slider {
        background-color: #ccc;
        bottom: 0;
        cursor: pointer;
        left: 0;
        position: absolute;
        right: 0;
        top: 0;
        transition: .4s;
    }

        .slider:before {
            background-color: #fff;
            bottom: 4px;
            content: "";
            height: 26px;
            left: 4px;
            position: absolute;
            transition: .4s;
            width: 26px;
        }

    input:checked + .slider {
        background-color: #66bb6a;
    }

        input:checked + .slider:before {
            transform: translateX(26px);
        }

    .slider.round {
        border-radius: 34px;
    }

        .slider.round:before {
            border-radius: 50%;
        }
</style>            

Proyecto_RadixWeb/Views/Asistencias/Create.cshtml
@model Proyecto_RadixWeb.Models.asistencias

@{
    ViewBag.Title = "Create";
}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-table"></i>Crear asistencia
            </div>
            <div class="card-body">
                <div class="table-responsive">

                    <h2>Create</h2>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>asistencias</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.Con_Id, "Con_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("Con_Id", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Con_Id, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Hl_Id, "Hl_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("Hl_Id", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Hl_Id, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.asis_estado, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <div class="checkbox">
                                        @Html.EditorFor(model => model.asis_estado)
                                        @Html.ValidationMessageFor(model => model.asis_estado, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                   </div>
                </div>
                <div class="card-footer small text-muted">Updated yesterday</div>
            </div>
        </div>
    </div>

Proyecto_RadixWeb/Views/Asistencias/Delete.cshtml
@model Proyecto_RadixWeb.Models.asistencias

@{
    ViewBag.Title = "Delete";
}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-table"></i> Eliminar asistencia
            </div>
            <div class="card-body">
                <div class="table-responsive">

                    <h2>Delete</h2>

                    <h3>Are you sure you want to delete this?</h3>
                    <div>
                        <h4>asistencias</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.asis_estado)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.asis_estado)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.contratos.Per_Rut)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.contratos.Per_Rut)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.horario_laboral.Hl_Titulo)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.horario_laboral.Hl_Titulo)
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-default" /> |
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        }
                    </div>
                    </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday</div>
        </div>
   </div>
</div>

Proyecto_RadixWeb/Views/Asistencias/Details.cshtml
@model Proyecto_RadixWeb.Models.asistencias

@{
    ViewBag.Title = "Details";
}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-table"></i> Detalles de asistencia
            </div>
            <div class="card-body">
                <div class="table-responsive">


                    <h2>Details</h2>

                    <div>
                        <h4>asistencias</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.asis_estado)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.asis_estado)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.contratos.Per_Rut)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.contratos.Per_Rut)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.horario_laboral.Hl_Titulo)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.horario_laboral.Hl_Titulo)
                            </dd>

                        </dl>
                    </div>
                    <p>
                        @Html.ActionLink("Edit", "Edit", new { id = Model.asis_id }) |
                        @Html.ActionLink("Back to List", "Index")
                    </p>
                </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday</div>
        </div>
    </div>
</div>

Proyecto_RadixWeb/Views/Asistencias/Edit.cshtml
@model Proyecto_RadixWeb.Models.asistencias

@{
    ViewBag.Title = "Edit";
}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-table"></i> Editar asistencia
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <h2>Edit</h2>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>asistencias</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.asis_id)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Con_Id, "Con_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("Con_Id", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Con_Id, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Hl_Id, "Hl_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("Hl_Id", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Hl_Id, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.asis_estado, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <div class="checkbox">
                                        @Html.EditorFor(model => model.asis_estado)
                                        @Html.ValidationMessageFor(model => model.asis_estado, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday</div>
        </div>
    </div>
</div>

Proyecto_RadixWeb/Views/Asistencias/Index.cshtml
@model IEnumerable<Proyecto_RadixWeb.Models.asistencias>

@{
    ViewBag.Title = "Index";
}
  </br>
    </br>
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-table"></i> Lista de Asistencia
                <div class="card-body">
                    <div class="table-responsive">

                        <h2>Asistencia</h2>

                        <p>
                            @Html.ActionLink("Agregar", "Create")
                        </p>
                        <table class="table">
                            <tr>
                                <th>
                                    R.U.T
                                </th>
                                <th>
                                    Nombre
                                </th>
                                <th>
                                    Apellidos
                                </th>

                                <th>
                                    Asistencia
                                </th>
                                <th></th>
                            </tr>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.contratos.Per_Rut)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.contratos.personas.Per_Nom)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.contratos.personas.Per_ApePat)
                                        @Html.DisplayFor(modelItem => item.contratos.personas.Per_ApeMat)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.horario_laboral.Hl_Inicio)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.horario_laboral.Hl_Termino)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.asis_estado)
                                    </td>


                                    <td>
                                        <label class="switch">
                                            <input id="togBtn" type="checkbox">
                                            <span class="slider round"></span>
                                        </label>
                                    </td>
                                </tr>
                            }

                        </table>
                    </div>
                </div>
                <div class="card-footer small text-muted">Updated yesterday</div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-3.3.1.js"></script>
<script>
    var switchStatus = false;
    $("#togBtn").on('change', function () {
        if ($(this).is(':checked')) {
            switchStatus = $(this).is(':checked');
            alert(switchStatus);// To verify
        }
        else {
            switchStatus = $(this).is(':checked');
            alert(switchStatus);// To verify
        }
    });
</script>
<style>
    .switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

        .switch input {
            display: none;
        }

    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }

        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }

    input:checked + .slider {
        background-color: #2196F3;
    }

    input:focus + .slider {
        box-shadow: 0 0 1px #2196F3;
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 34px;
    }

        .slider.round:before {
            border-radius: 50%;
        }
</style>