Proyecto_RadixWeb/Models/Sectores.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sectores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sectores()
        {
            this.Cuarteles = new HashSet<Cuarteles>();
        }
    
        public int sect_id { get; set; }
        public string sect_nom { get; set; }
        public Nullable<int> Sub_Id { get; set; }
    
        public virtual subempresas subempresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuarteles> Cuarteles { get; set; }
    }
}

Proyecto_RadixWeb/Controllers/SectoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_RadixWeb.Models;

namespace Proyecto_RadixWeb.Controllers
{
    public class SectoresController : Controller
    {
        private radixEntities db = new radixEntities();

        // GET: Sectores
        public ActionResult Index(string subemp_id)
        {

            ViewBag.subemp_id = subemp_id;
            int sub = Convert.ToInt32(subemp_id.ToString());
            var sectores = db.Sectores.Include(s => s.subempresas);

            MultiplesClases multiples = new MultiplesClases
            {
                ObjESectores = sectores.Where(e => e.Sub_Id == sub).OrderBy(s=>s.sect_nom).ToList()
            };

            return View(multiples);
        }
        public ActionResult All()
        {

            string emp_nom = HttpContext.Session["Empresa"].ToString();
            int emp_id = Convert.ToInt32(HttpContext.Session["Emp_id"].ToString());
            ViewBag.empresa = emp_nom;
          
            int contar4 = db.Sectores.Count(s => s.subempresas.empresas.Emp_Id == emp_id);
            ViewBag.contarsectores = contar4;
            var sec = db.Sectores.Include(c => c.subempresas);
            MultiplesClases multiples = new MultiplesClases
            {
                ObjESectores = sec.Where(s => s.subempresas.empresas.Emp_Nom == emp_nom).OrderBy(c=>c.sect_nom).ToList()
            };

            return View(multiples);
        }
        // GET: Sectores/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sectores sectores = db.Sectores.Find(id);
            if (sectores == null)
            {
                return HttpNotFound();
            }
            return View(sectores);
        }

        // GET: Sectores/Create
        public ActionResult Create()
        {
            ViewBag.Sub_Id = new SelectList(db.subempresas, "Sub_Id", "Sub_Nom");
            return View();
        }

        // POST: Sectores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MultiplesClases multiples, string subemp_id)
        {
            if (ModelState.IsValid)
            {
                multiples.ObjSectores.Sub_Id = Convert.ToInt32(subemp_id);
                db.Sectores.Add(multiples.ObjSectores);
                db.SaveChanges();
                return RedirectToAction("Index",new { subemp_id });
            }

            ViewBag.Sub_Id = new SelectList(db.subempresas, "Sub_Id", "Sub_Nom", multiples.ObjSectores.Sub_Id);
            return View(multiples);
        }

        // GET: Sectores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sectores sectores = db.Sectores.Find(id);
            if (sectores == null)
            {
                return HttpNotFound();
            }
            ViewBag.Sub_Id = new SelectList(db.subempresas, "Sub_Id", "Sub_Nom", sectores.Sub_Id);
            return View(sectores);
        }

        // POST: Sectores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "sect_id,sect_nom,Sub_Id")] Sectores sectores)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sectores).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Sub_Id = new SelectList(db.subempresas, "Sub_Id", "Sub_Nom", sectores.Sub_Id);
            return View(sectores);
        }

        // GET: Sectores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sectores sectores = db.Sectores.Find(id);
            if (sectores == null)
            {
                return HttpNotFound();
            }
            return View(sectores);
        }
       [HttpPost]
        public ActionResult borrar(int id) {
       
            Sectores sectores = db.Sectores.Find(id);
            db.Sectores.Remove(sectores);
            db.SaveChanges();

            return View("Index");
        }
        // POST: Sectores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sectores sectores = db.Sectores.Find(id);
            db.Sectores.Remove(sectores);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Eliminar(Sectores sect, string subemp_id)
        {
            int? id2 = sect.sect_id;
            int id = Convert.ToInt32(id2);

            var cuarteles = db.Cuarteles.Where(c => c.sect_id == id);

            foreach (var item in cuarteles)
            {
                var grupos = db.GruposCuarteles.Where(gc => gc.cuar_id == item.cuar_id);


                if (grupos != null)
                {

                    foreach (var item2 in grupos)
                    {
                        var grupodetalle = db.GrupoCuartelesDetalle.Where(gd=>gd.gc_id==item2.gc_id);

                        if (grupodetalle!=null)
                        {
                            foreach (var item3 in grupodetalle)
                            {
                                GrupoCuartelesDetalle detalle = db.GrupoCuartelesDetalle.Find(item3.gc_id);
                                db.GrupoCuartelesDetalle.Remove(detalle);
                            }
                           
                        }

                        GruposCuarteles gc = db.GruposCuarteles.Find(item2.gc_id);
                        db.GruposCuarteles.Remove(gc);
                    }
                  
                }

                Cuarteles ca = db.Cuarteles.Find(item.cuar_id);
                db.Cuarteles.Remove(ca);
            }
            db.SaveChanges();

            Sectores sectores = db.Sectores.Find(id);
            db.Sectores.Remove(sectores);
            db.SaveChanges();
            return RedirectToAction("Index",new { subemp_id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto_RadixWeb/Views/Sectores/All.cshtml
@model Proyecto_RadixWeb.Models.MultiplesClases

@{
    ViewBag.Title = "Index Sectores";
}
<link href="~/Content/css/dashboard/app.css" rel="stylesheet" />

<div id="contenido_vista" @*style="margin-top: 10%;margin-left:10%"*@>
    <article class="content responsive-tables-page">
        <div class="title-block">
            <div class="">
            </div>
            <div class="col col-xs-12 col-md-9 col-lg-9">
                <h1 class="title" style="text-align:center"><i class="fas fa-map-marked-alt"></i>   Sectores de la empresa @ViewBag.empresa </h1>
            </div> 
     
        </div>
        <section class="section">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-block">
                            <div class="card-title-block">

                            </div>
                            <section class="example">
                                <div class="table-flip-scroll">
                                    <table class="table table-striped table-bordered table-hover flip-content">
                                        <thead class=" thead-inverse">
                                            <tr>
                                                <th>
                                                    Nombre
                                                </th>
                                                <th>Ubicacion</th>
                                              
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr class="odd gradeX">
                                                @foreach (var item in Model.ObjESectores)
                                                {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.sect_nom)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.subempresas.Sub_Nom)
                                                    </td>
                                               
                                                </tr>
                                            }


                                            </tbody>
                                        </table>
                                    </div>
                                </section>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </article>



    </div>
    



    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script>

    $(document).ready(function () {

        $('#contenido_vista').appendTo('#contenido_general');
    });
    $(".sectoreliminar").on("click", function () {

        $("#sect_id").val($(this).attr("id"));
        var nom = $(this).attr("name");
        document.getElementById("nombresector").innerHTML = nom;
        //$("#nombresector").val($(this).attr("name"));
    });
    </script>

Proyecto_RadixWeb/Views/Sectores/Create.cshtml
@model Proyecto_RadixWeb.Models.Sectores

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sectores</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.sect_nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sect_nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sect_nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sub_Id, "Sub_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Sub_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sub_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Proyecto_RadixWeb/Views/Sectores/Delete.cshtml
@model Proyecto_RadixWeb.Models.Sectores

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sectores</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.sect_nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sect_nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.subempresas.Sub_Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.subempresas.Sub_Nom)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Proyecto_RadixWeb/Views/Sectores/Details.cshtml
@model Proyecto_RadixWeb.Models.Sectores

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Sectores</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.sect_nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sect_nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.subempresas.Sub_Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.subempresas.Sub_Nom)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.sect_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Proyecto_RadixWeb/Views/Sectores/Edit.cshtml
@model Proyecto_RadixWeb.Models.Sectores

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sectores</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.sect_id)

        <div class="form-group">
            @Html.LabelFor(model => model.sect_nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sect_nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sect_nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sub_Id, "Sub_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Sub_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sub_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Proyecto_RadixWeb/Views/Sectores/Index.cshtml
@model Proyecto_RadixWeb.Models.MultiplesClases

@{
    ViewBag.Title = "Index Sectores";
}


<div id="contenido_vista" @*style="margin-top: 10%;margin-left:10%"*@>
    <article class="content responsive-tables-page">
        <div class="title-block">
            <div class="">
            </div>
            <div class="col col-xs-12 col-md-9 col-lg-9">
                <h1 class="title" style="text-align:center"><i class="fas fa-map-marked-alt"></i>   Sectores de la empresa @ViewBag.empresa </h1>
            </div>
            <div class="col col-xs-3 col-md-3 col-lg-3 text-right">
                <a class="btn btn-primary text-white" data-toggle="modal" data-target="#MiModal"><i class="fas fa-user-plus"></i> Agregar Cuenta </a>

            </div>
        </div>
        <section class="section">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-block">
                            <div class="card-title-block">

                            </div>
                            <section class="example">
                                <div class="table-flip-scroll">
                                    <table class="table table-striped table-bordered table-hover flip-content">
                                        <thead class=" thead-inverse">
                                            <tr>
                                                <th>
                                                    Nombre
                                                </th>
                                                <th>Ubicacion</th>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                             
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr class="odd gradeX">
                                                @foreach (var item in Model.ObjESectores)
                                                {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.sect_nom)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.subempresas.Sub_Nom)
                                                    </td>
                                                    @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.pc_id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.pc_id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.pc_id })
                </td>*@
                                                    <td align="center">

                                                        <a class="btn btn-outline-secondary" data-toggle="modal" data-target="#modaleditar"><i class="fas fa-edit"></i></a>
                                                    </td>
                                                    <td align="center">
                                                        <a class="btn btn-danger sectoreliminar" id="@item.sect_id" name="@item.sect_nom" href="#" data-toggle="modal" data-target="#Misectoreliminar"><i class="fas fa-trash-alt"></i></a>
                                                    </td>
                                                    <th>
                                                        <a href="@Url.Action("Index", "Cuarteles", new { sect_id = item.sect_id,subemp_id=ViewBag.subemp_id })" class="mt-2"><i class="fas fa-map-marker-alt btn btn-warning" style="margin-left: 25%;"> Cuadrillas</i></a>
                                                    </th>
                                                    @*<th>
                                                        <a class="btn btn-outline-success btn-sm m-0 sectoreliminar" id="@item.sect_id" href="#" data-toggle="modal" data-target="#Misectoreliminar">
                                                            Agregar Contrato
                                                        </a>
                                                    </th>*@
                                                </tr>
                                                }


                                            </tbody>
                                        </table>
                                    </div>
                                </section>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </article>



    </div>
    <!-- Create -->
    <div class="modal fade" id="MiModal" tabindex="-1" role="dialog" aria-labelledby="MiModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            @using (Html.BeginForm("Create", "Sectores", new { subemp_id = ViewBag.subemp_id }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title col-sm-11 col-md-11 col-lg-11 col-xl-11">Nuevo Sector</h4>
                        <button type="button" class="close col-sm-1 col-md-1 col-lg-1 col-xl-1" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <!--Contenido del centro-->
                    <div class="modal-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.Label("Sector")
                            @Html.EditorFor(model => model.ObjSectores.sect_nom, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </div>
            }
        </div>
    </div>
    <!--Eliminar-->
    <div class="modal fade" id="Misectoreliminar" tabindex="-1" role="dialog" aria-labelledby="Misectoreliminar" aria-hidden="true">
        <div class="modal-dialog" role="document">
            @using (Html.BeginForm("Eliminar", "Sectores", new { subemp_id= ViewBag.subemp_id }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title col-sm-11 col-md-11 col-lg-11 col-xl-11">¿Desea Eliminar El Sector <label id="nombresector"></label> ?</h4>
                        <button type="button" class="modal-title close col-sm-1 col-md-1 col-lg-1 col-xl-1" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <!--Contenido del centro-->
                
                        @Html.Hidden("sect_id")
                    
                    <div class="modal-footer">
                       @* <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>*@
                        <button type="submit" class="btn btn-primary">Eliminar</button>
                    </div>
                </div>
            }
        </div>
    </div>



<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script> 
    $(document).ready(function () {

        $('#contenido_vista').appendTo('#contenido_general');
    });
    $(".sectoreliminar").on("click", function () {

        $("#sect_id").val($(this).attr("id"));
        var nom = $(this).attr("name");
        document.getElementById("nombresector").innerHTML = nom;
        //$("#nombresector").val($(this).attr("name"));
    });
</script>