Proyecto_RadixWeb/Models/planillascontratos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class planillascontratos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public planillascontratos()
        {
            this.empresa_cargo = new HashSet<empresa_cargo>();
        }
    
        public int PC_Id { get; set; }
        public string PC_Nom { get; set; }
        public string PC_Ext { get; set; }
        public byte[] PC_Binario { get; set; }
        public int empcar_id { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empresa_cargo> empresa_cargo { get; set; }
    }
}

Proyecto_RadixWeb/Controllers/planillascontratosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_RadixWeb.Models;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using System.Diagnostics;
using System.Text;

namespace Proyecto_RadixWeb.Controllers
{
    public class PlanillascontratosController : Controller
    {
        private radixEntities db = new radixEntities();

      
        public ActionResult SubirArchivo()
        {
            return View();
        }

        public ActionResult SubirArchivo_v2()
        {
            return View();
        }


        // GET: planillascontratos
        public ActionResult Index(string emp_id)
        {
            ViewBag.emp_id = Convert.ToInt32(emp_id);
            ViewBag.empresa = HttpContext.Session["Empresa"].ToString();
            int emp_id2 = Convert.ToInt32(HttpContext.Session["Emp_id"].ToString());
            

            try
            {
                ViewBag.sms = TempData["sms"].ToString();
            }
            catch
            {
            }

            try
            {
                ViewBag.smserror = TempData["smserror"].ToString();
            }
            catch 
            {
            }

          
            return View(db.planillascontratos.ToList());
        }
        public ActionResult allPlanillas()
        {
            string emp_nom = HttpContext.Session["Empresa"].ToString();

            ViewBag.emp_id = HttpContext.Session["Emp_id"].ToString();
            ViewBag.empresa = emp_nom;

            List<planillascontratos> listarc = db.planillascontratos.ToList();
            ViewBag.contratos = new SelectList(listarc, "Cod_Id", "Sub_Id", "Per_Rut");


            var contratos = db.contratos.Include(s => s.subempresas).Include(s => s.personas).Include(s => s.subempresas.empresas);
            MultiplesClases multiples = new MultiplesClases
            {
                ObjEContrato = contratos.Where(s => s.subempresas.empresas.Emp_Nom == emp_nom).ToList()
            };

            return View(multiples);
        }


        public ActionResult DescargarDocx(int? id)
        {

            var archivo = db.planillascontratos.Where(p => p.PC_Id == id).FirstOrDefault();

         
            return File(archivo.PC_Binario, "document/docx", archivo.PC_Nom + ".docx");

        }

        public ActionResult DescargarPdf(int? id)
        {
            var archivo = db.planillascontratos.Where(dp => dp.PC_Id == id).FirstOrDefault();
            // Configure API key authorization: Apikey
            Configuration.Default.AddApiKey("Apikey", "768fa287-07a9-41f9-962d-d1b9356a6b04");
            ConvertDocumentApi apiInstance = new ConvertDocumentApi();
            //convertir un binario a system.io.stream
            MemoryStream stream = new MemoryStream(archivo.PC_Binario);
            try
            {
                // convertir
                byte[] result = apiInstance.ConvertDocumentDocxToPdf(stream);
                return File(result, "document/pdf", archivo.PC_Nom + ".pdf");
            }
            catch (Exception e)
            {
                Debug.Print("Error al convertir : " + e.Message);
            }
            return View();
        }
        // GET: planillascontratos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            planillascontratos planillascontratos = db.planillascontratos.Find(id);
            if (planillascontratos == null)
            {
                return HttpNotFound();
            }
            return View(planillascontratos);
        }

        // GET: planillascontratos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: planillascontratos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PC_Id,PC_Nom")] planillascontratos planillascontratos, HttpPostedFileBase plantilla)
        {
            if (plantilla != null && plantilla.ContentLength > 0)
            {
                var length = plantilla.InputStream.Length; //Length: 103050706
             

                byte[] datoplantilla = null;
                using (var binarydoc = new BinaryReader(plantilla.InputStream))
                {
                    datoplantilla = binarydoc.ReadBytes(plantilla.ContentLength);
                }
                planillascontratos.PC_Binario = datoplantilla;
                planillascontratos.PC_Ext = Path.GetExtension(plantilla.FileName);
            }

            if (ModelState.IsValid)
            {
                //planillascontratos.PC_Ext =".docx";
             

                try
                {
                    db.planillascontratos.Add(planillascontratos);
                    db.SaveChanges();

                    TempData["sms"] = "Se guardo la plantilla";
                    ViewBag.sms = TempData["sms"];
                    return RedirectToAction("Index");
                }
                catch 
                {

                    TempData["smserror"] = "No se pudo guardar la plantilla";
                    ViewBag.smserror = TempData["smserror"];
                    return RedirectToAction("Index");
                }
              
            }

            return View(planillascontratos);
        }


      
        // GET: planillascontratos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            planillascontratos planillascontratos = db.planillascontratos.Find(id);
            if (planillascontratos == null)
            {
                return HttpNotFound();
            }
            return View(planillascontratos);
        }

        // POST: planillascontratos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PC_Id,PC_Nom,PC_Ext,PC_Binario")] planillascontratos planillascontratos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(planillascontratos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(planillascontratos);
        }

        // GET: planillascontratos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            planillascontratos planillascontratos = db.planillascontratos.Find(id);
            if (planillascontratos == null)
            {
                return HttpNotFound();
            }
            return View(planillascontratos);
        }

        // POST: planillascontratos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            planillascontratos planillascontratos = db.planillascontratos.Find(id);
            db.planillascontratos.Remove(planillascontratos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto_RadixWeb/Views/planillascontratos/Create.cshtml
@model Proyecto_RadixWeb.Models.planillascontratos

@{
    ViewBag.Title = "Create";
}
<link href="~/Content/estilo.css" rel="stylesheet" />

<script src="~/Scripts/dropzone/dropzone.js"></script>
<link href="~/Scripts/dropzone/dropzone.css" rel="stylesheet" />


<div class="content-wrapper">
    <div class="container-fluid">
        <div class="card mb-3">
            </br>
            
            </br>
            <div class="card-header">


                <i class="fa fa-table"></i> Data Table Example
            </div>
            <div class="card-body">
                <div class="table-responsive">

                    @if (ViewBag.sms != null)
                    {
                    <div class="alert alert-success">
                        <strong>Success!</strong> Indicates a successful or positive action.@ViewBag.sms
                    </div>
                    }
                    @if (ViewBag.smserror != null)
                    {
                        <div class="alert alert-warning">
                            <strong>Warning!</strong> Indicates a warning that might need attention.@ViewBag.smserror
                        </div>
                    }

                    @using (Html.BeginForm("Create", "Planillascontratos", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()



                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="input-group " style="margin-left: 80px;width: 450px;margin-bottom: 10px;">
                            <div class="input-group-prepend">
                                <span class="input-group-text " id="" style="width: 150px;">Titulo Archivo</span>
                            </div>
                            @Html.EditorFor(model => model.PC_Nom, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PC_Nom, "", new { @class = "text-danger" })

                        </div>

                        <div class="input-group" style="margin-left: 80px;width: 450px;margin-bottom: 10px;">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="" style="width: 150px;">Estado</span>
                            </div>
                            <div style="background-color: white;">
                                <input type="file" name="plantilla" style="width: 300px;margin-left: 1px;margin-top: 5px;" />
                            </div>
                        </div>



                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-primary" style=" margin-left: 250px;" />
                            </div>
                        </div>


                    }





                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>

                    @section Scripts {
                        @Scripts.Render("~/bundles/jqueryval")
                    }

                </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
        </div>
    </div>
</div>

Proyecto_RadixWeb/Views/planillascontratos/Delete.cshtml
@model Proyecto_RadixWeb.Models.planillascontratos

@{
    ViewBag.Title = "Delete";
}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-table"></i> Eliminar plantillas de contratos
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <h2>Delete</h2>

                    <h3>Are you sure you want to delete this?</h3>
                    <div>
                        <h4>planillascontratos</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.PC_Nom)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.PC_Nom)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.PC_Ext)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.PC_Ext)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.PC_Binario)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.PC_Binario)
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-default" /> |
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday</div>
        </div>
    </div>
</div>

Proyecto_RadixWeb/Views/planillascontratos/Details.cshtml
@model Proyecto_RadixWeb.Models.planillascontratos

@{
    ViewBag.Title = "Details";
}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-table"></i> Detalles de las plantillas
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <h2>Details</h2>

                    <div>
                        <h4>plantillascontratos</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.PC_Nom)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.PC_Nom)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.PC_Ext)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.PC_Ext)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.PC_Binario)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.PC_Binario)
                            </dd>

                        </dl>
                    </div>
                    <p>
                        @Html.ActionLink("Edit", "Edit", new { id = Model.PC_Id }) |
                        @Html.ActionLink("Back to List", "Index")
                    </p>
                </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday</div>
        </div>
    </div>
</div>

Proyecto_RadixWeb/Views/planillascontratos/Edit.cshtml
@model Proyecto_RadixWeb.Models.planillascontratos

@{
    ViewBag.Title = "Edit";
}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-table"></i> Editar nombres de las plantillas
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <h2>Edit</h2>


                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>planillascontratos</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.PC_Id)

                            <div class="form-group">
                                @Html.LabelFor(model => model.PC_Nom, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.PC_Nom, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.PC_Nom, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.PC_Ext, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.PC_Ext, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.PC_Ext, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.PC_Binario, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.PC_Binario, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.PC_Binario, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>

                    @section Scripts {
                        @Scripts.Render("~/bundles/jqueryval")
                    }
                </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday</div>
        </div>
    </div>
</div>

Proyecto_RadixWeb/Views/planillascontratos/Index.cshtml
@model IEnumerable<Proyecto_RadixWeb.Models.planillascontratos>

@{
    ViewBag.Title = "Index";
}

<div id="contenido_vista" style="margin-top: 10%;margin-left:10%">
    <div class="card mb-3 mt-2" style="border: 1px solid;">
        <div class="card-header">
            <div class="col col-xs-1 col-md-1 col-lg-1">
                <i class="fas fa-table"></i>
            </div>
            <div class="col col-xs-8 col-md-8 col-lg-8">
                <h5 class="panel-title" style="text-align:center"><b>Documentos</b> </h5>
            </div>
            <div class="col col-xs-3 col-md-3 col-lg-3 text-right">
                <button class="btn btn-sm btn-danger" href="@Url.Action("Create", "planillascontratos")">Agregar Documento </button>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                @if (ViewBag.sms != null)
                {
                    <div class="alert alert-success">
                        <strong>Success!</strong> Indicates a successful or positive action.@ViewBag.sms
                    </div>
                }
                @if (ViewBag.smserror != null)
                {
                    <div class="alert alert-warning">
                        <strong>Warning!</strong> Indicates a warning that might need attention.@ViewBag.smserror
                    </div>
                }

                <table class="table table-hover table-bordered table-condensed">
                    <tr style="background-color:#d7d6d6">
                        <th>
                            Nombre Documento
                        </th>
                        <th>
                            Extension
                        </th>
                        <th>
                            Descargar
                        </th>
                        <th></th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.PC_Nom)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PC_Ext)
                            </td>

                            <td>
                                @Html.ActionLink("Descargar Docx", "DescargarDocx", new { id = item.PC_Id })  |
                                @Html.ActionLink("Descargar Pdf", "DescargarPdf", new { id = item.PC_Id })
                            </td>
                            <td align="center">

                                <a class="btn btn-outline-secondary" data-toggle="modal" data-target="#modaleditar"><i class="fas fa-edit"></i></a>
                            </td>
                            <td align="center">
                                <a class="btn btn-danger" data-toggle="modal" data-target="#modaleliminar"><i class="fas fa-trash-alt"></i></a>
                            </td>
                        </tr>
                    }


                </table>
            </div>
        </div>
    </div>
</div>

<!--editar-->
<!-- Modal -->
<div class="modal fade" id="modaleditar" tabindex="-1" role="dialog" aria-labelledby="modaleditar" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Editar</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!--eliminar--><!-- Modal -->
<div class="modal fade" id="modaleliminar" tabindex="-1" role="dialog" aria-labelledby="modaleliminar" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Eliminar</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>



<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>

    $(document).ready(function () {
        $('#contenido_vista').appendTo('#contenido_general');
    });

</script>

Proyecto_RadixWeb/Views/planillascontratos/SubirArchivo.cshtml
@{
    ViewBag.Title = "SubirArchivo";
}
<link href="~/Scripts/dropzone/dropzone.css" rel="stylesheet" />
<link href="~/Scripts/dropzone/basic.css" rel="stylesheet" />
<div id="pagina" style="height: 256px;width: 1000px;margin-left: 284px;margin-top: 170px;">


   

    <h1>DropzoneJS File Upload Demo</h1>
   
        <div id="dropzone">
            <form class="dropzone needsclick" id="demo-upload" action="/upload">
                <div class="dz-message needsclick">
                    Drop files here or click to upload.<BR>
                    <spam class="note needsclick">
                        (This is just a demo dropzone. Selected
                        files are <strong>not</strong> actually uploaded.)
                    </spam>
                </div>
            </form>
        </div>
 

 
   
</div>



<style>
    body {
        background: rgb(243, 244, 245);
        height: 100%;
        color: rgb(100, 108, 127);
        line-height: 1.4rem;
        font-family: Roboto, "Open Sans", sans-serif;
        font-size: 20px;
        font-weight: 300;
        text-rendering: optimizeLegibility;
    }

    h1 {
        text-align: center;
    }

    .dropzone {
        background: white;
        border-radius: 5px;
        border: 2px dashed rgb(0, 135, 247);
        border-image: none;
        max-width: 500px;
        margin-left: auto;
        margin-right: auto;
    }
</style>

<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/dropzone/dropzone.js"></script>

<script>

    var dropzone = new Dropzone('#demo-upload', {
        previewTemplate: document.querySelector('#preview-template').innerHTML,
        parallelUploads: 2,
        thumbnailHeight: 120,
        thumbnailWidth: 120,
        maxFilesize: 3,
        filesizeBase: 1000,
        thumbnail: function (file, dataUrl) {
            if (file.previewElement) {
                file.previewElement.classList.remove("dz-file-preview");
                var images = file.previewElement.querySelectorAll("[data-dz-thumbnail]");
                for (var i = 0; i < images.length; i++) {
                    var thumbnailElement = images[i];
                    thumbnailElement.alt = file.name;
                    thumbnailElement.src = dataUrl;
                }
                setTimeout(function () { file.previewElement.classList.add("dz-image-preview"); }, 1);
            }
        }

    });


    // Now fake the file upload, since GitHub does not handle file uploads
    // and returns a 404

    var minSteps = 6,
        maxSteps = 60,
        timeBetweenSteps = 100,
        bytesPerStep = 100000;

    dropzone.uploadFiles = function (files) {
        var self = this;

        for (var i = 0; i < files.length; i++) {

            var file = files[i];
            totalSteps = Math.round(Math.min(maxSteps, Math.max(minSteps, file.size / bytesPerStep)));

            for (var step = 0; step < totalSteps; step++) {
                var duration = timeBetweenSteps * (step + 1);
                setTimeout(function (file, totalSteps, step) {
                    return function () {
                        file.upload = {
                            progress: 100 * (step + 1) / totalSteps,
                            total: file.size,
                            bytesSent: (step + 1) * file.size / totalSteps
                        };

                        self.emit('uploadprogress', file, file.upload.progress, file.upload.bytesSent);
                        if (file.upload.progress === 100) {
                            file.status = Dropzone.SUCCESS;
                            self.emit("success", file, 'success', null);
                            self.emit("complete", file);
                            self.processQueue();
                            //document.getElementsByClassName("dz-success-mark").style.opacity = "1";
                        }
                    };
                }(file, totalSteps, step), duration);
            }
        }
    }
</script>

Proyecto_RadixWeb/Views/planillascontratos/SubirArchivo_v2.cshtml
@{
    ViewBag.Title = "SubirArchivo_v2";
}