Proyecto_RadixWeb/Models/GruposCuarteles.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GruposCuarteles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GruposCuarteles()
        {
            this.GrupoCuartelesDetalle = new HashSet<GrupoCuartelesDetalle>();
        }
    
        public int gc_id { get; set; }
        public Nullable<int> cuar_id { get; set; }
        public string gc_nom { get; set; }
        public Nullable<int> ConJefe_id { get; set; }
    
        public virtual contratos contratos { get; set; }
        public virtual Cuarteles Cuarteles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoCuartelesDetalle> GrupoCuartelesDetalle { get; set; }
    }
}

Proyecto_RadixWeb/Controllers/GruposCuartelesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_RadixWeb.Models;

namespace Proyecto_RadixWeb.Controllers
{
    public class GruposCuartelesController : Controller
    {
        private radixEntities db = new radixEntities();

        // GET: GruposCuarteles
        public ActionResult Index(string cuar_id,string subemp_id)
        {
            ViewBag.subemp_id = subemp_id;
            ViewBag.cuar_id = cuar_id;
            int cuar = Convert.ToInt32(cuar_id.ToString());

            var listacuar = db.Cuarteles.FirstOrDefault(c=>c.cuar_id== cuar);

            int? subemp = listacuar.Sectores.Sub_Id;

            int sub_id =Convert.ToInt32(subemp);


            var listajefes = db.contratos.Where(c=>c.personas.cargos.Car_Nom== "Jefe Cuadrilla").Select(v => new {
                Con_id = v.Con_Id,
                NombreJefe = v.personas.Per_Nom + " " + v.personas.Per_ApePat
            });

            ViewBag.ObjGruposCuarteles_ConJefe_id = new SelectList(listajefes, "Con_id", "NombreJefe");


            var grupos = db.GruposCuarteles.Include(c => c.Cuarteles).Include(p=>p.contratos);
            MultiplesClases multiples = new MultiplesClases
            {
                ObjEGruposCuarteles = grupos.Where(e => e.cuar_id == cuar).ToList()
            };
            return View(multiples);
        }

        // GET: GruposCuarteles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GruposCuarteles gruposCuarteles = db.GruposCuarteles.Find(id);
            if (gruposCuarteles == null)
            {
                return HttpNotFound();
            }
            return View(gruposCuarteles);
        }

        // GET: GruposCuarteles/Create
        public ActionResult Create()
        {
            ViewBag.Con_id = new SelectList(db.contratos, "Con_Id", "Per_Rut");
            ViewBag.ConJefe_id = new SelectList(db.contratos, "Con_Id", "Per_Rut");
            ViewBag.cuar_id = new SelectList(db.Cuarteles, "cuar_id", "cuar_nom");
            return View();
        }

        // POST: GruposCuarteles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MultiplesClases multiples,string cuar_id)
        {
            if (ModelState.IsValid)
            {
                multiples.ObjGruposCuarteles.cuar_id = Convert.ToInt32(cuar_id);


                db.GruposCuarteles.Add(multiples.ObjGruposCuarteles);
                db.SaveChanges();
                return RedirectToAction("Index",new { cuar_id});
            }

        
            return View(multiples);
        }

        // GET: GruposCuarteles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GruposCuarteles gruposCuarteles = db.GruposCuarteles.Find(id);
            if (gruposCuarteles == null)
            {
                return HttpNotFound();
            }
         
            ViewBag.ConJefe_id = new SelectList(db.contratos, "Con_Id", "Per_Rut", gruposCuarteles.ConJefe_id);
            ViewBag.cuar_id = new SelectList(db.Cuarteles, "cuar_id", "cuar_nom", gruposCuarteles.cuar_id);
            return View(gruposCuarteles);
        }

        // POST: GruposCuarteles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "gc_id,cuar_id,Con_id,ConJefe_id")] GruposCuarteles gruposCuarteles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gruposCuarteles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
          
            ViewBag.ConJefe_id = new SelectList(db.contratos, "Con_Id", "Per_Rut", gruposCuarteles.ConJefe_id);
            ViewBag.cuar_id = new SelectList(db.Cuarteles, "cuar_id", "cuar_nom", gruposCuarteles.cuar_id);
            return View(gruposCuarteles);
        }

        // GET: GruposCuarteles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GruposCuarteles gruposCuarteles = db.GruposCuarteles.Find(id);
            if (gruposCuarteles == null)
            {
                return HttpNotFound();
            }
            return View(gruposCuarteles);
        }

        // POST: GruposCuarteles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GruposCuarteles gruposCuarteles = db.GruposCuarteles.Find(id);
            db.GruposCuarteles.Remove(gruposCuarteles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Eliminar(GruposCuarteles grup, string cuar_id)
        {
            int? id2 = grup.gc_id;
            int id = Convert.ToInt32(id2);

            GruposCuarteles gc = db.GruposCuarteles.Find(id);
            db.GruposCuarteles.Remove(gc);
            db.SaveChanges();
            return RedirectToAction("Index", new { cuar_id });
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proyecto_RadixWeb/Views/GruposCuarteles/Create.cshtml
@model Proyecto_RadixWeb.Models.GruposCuarteles

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>GruposCuarteles</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.cuar_id, "cuar_id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("cuar_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.cuar_id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Con_id, "Con_id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Con_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Con_id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ConJefe_id, "ConJefe_id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ConJefe_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ConJefe_id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Proyecto_RadixWeb/Views/GruposCuarteles/Delete.cshtml
@model Proyecto_RadixWeb.Models.GruposCuarteles

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>GruposCuarteles</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.contratos.Per_Rut)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.contratos.Per_Rut)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.contratos1.Per_Rut)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.contratos1.Per_Rut)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Cuarteles.cuar_nom)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Cuarteles.cuar_nom)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Proyecto_RadixWeb/Views/GruposCuarteles/Details.cshtml
@model Proyecto_RadixWeb.Models.GruposCuarteles

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>GruposCuarteles</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.contratos.Per_Rut)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.contratos.Per_Rut)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.contratos1.Per_Rut)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.contratos1.Per_Rut)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Cuarteles.cuar_nom)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Cuarteles.cuar_nom)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.gc_id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Proyecto_RadixWeb/Views/GruposCuarteles/Edit.cshtml
@model Proyecto_RadixWeb.Models.GruposCuarteles

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>GruposCuarteles</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.gc_id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.cuar_id, "cuar_id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("cuar_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.cuar_id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Con_id, "Con_id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Con_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Con_id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ConJefe_id, "ConJefe_id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ConJefe_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ConJefe_id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Proyecto_RadixWeb/Views/GruposCuarteles/Index.cshtml
@model Proyecto_RadixWeb.Models.MultiplesClases

@{
    ViewBag.Title = "Index grupos";
}




<div id="contenido_vista" @*style="margin-top: 10%;margin-left:10%"*@>
    <article class="content responsive-tables-page">
        <div class="title-block">
            <div class="">
            </div>
            <div class="col col-xs-12 col-md-9 col-lg-9">
                <h1 class="title" style="text-align:center"><i class="fas fa-user-friends"></i>  Encargados de Grupos de trabajadores de la empresa @ViewBag.empresa </h1>
            </div>
            <div class="col col-xs-3 col-md-3 col-lg-3 text-right">
                <a class="btn btn-primary text-white addGrupos" data-toggle="modal" data-target="#MiaddGrupo"><i class="fas fa-user-plus"></i> Crear Grupo </a>

            </div>
        </div>
        <section class="section">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-block">
                            <div class="card-title-block">

                            </div>
                            <section class="example">
                                <div class="table-flip-scroll">
                                    <table class="table table-striped table-bordered table-hover flip-content">
                                        <thead class=" thead-inverse">
                                            <tr>
                                                <th>
                                                    Encargado
                                                </th>

                                                <th>
                                                    Cuadrilla
                                                </th>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr class="odd gradeX">
                                                @foreach (var item in Model.ObjEGruposCuarteles)
                                                {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.contratos.personas.Per_Nom)
                                                        @Html.DisplayFor(modelItem => item.contratos.personas.Per_ApePat)

                                                    </td>
                                                    @*<td>
                                                            @Html.DisplayFor(modelItem => item.contratos1.personas.Per_Nom)
                                                            @Html.DisplayFor(modelItem => item.contratos1.personas.Per_ApePat)
                                                        </td>*@
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Cuarteles.cuar_nom)
                                                    </td>
                                                    <td align="center">

                                                        <a class="btn btn-outline-secondary" data-toggle="modal" data-target="#modaleditar"><i class="fas fa-edit"></i></a>
                                                    </td>
                                                    <td align="center">
                                                        <a class="btn btn-danger sectoreliminar" id="@item.gc_id" name="@item.Cuarteles.cuar_nom" href="#" data-toggle="modal" data-target="#Misectoreliminar"><i class="fas fa-trash-alt"></i></a>
                                                    </td>
                                                    <td align="center">
                                                        <a class="btn btn-primary" href="@Url.Action("Index","GrupoCuartelesDetalles",new { gc_id=item.gc_id,subemp_id=ViewBag.subemp_id })">Mi Grupo</a>
                                                    </td>
                                                    @*<td>
                                                            @Html.ActionLink("Edit", "Edit", new { id = item.gc_id }) |
                                                            @Html.ActionLink("Details", "Details", new { id = item.gc_id }) |
                                                            @Html.ActionLink("Delete", "Delete", new { id = item.gc_id })
                                                        </td>*@
                                                </tr>
                                            }


                                            </tbody>
                                        </table>
                                    </div>
                                </section>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </article>



    </div>
    <!-- Create -->
    <div class="modal fade" id="MiaddGrupo" tabindex="-1" role="dialog" aria-labelledby="MiaddGrupo" aria-hidden="true">
        <div class="modal-dialog" role="document">
            @using (Html.BeginForm("Create", "GruposCuarteles", new { cuar_id = ViewBag.cuar_id }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Nuevo Grupo</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <!--Contenido del centro-->
                    <div class="modal-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.Label("Grupo")
                            @Html.EditorFor(model => model.ObjGruposCuarteles.gc_nom, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            @Html.Label("Encargado", htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.DropDownList("ObjGruposCuarteles_ConJefe_id", null, htmlAttributes: new { @class = "form-control" })
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </div>
            }
        </div>
    </div>

    <!--Eliminar-->
    <div class="modal fade" id="Misectoreliminar" tabindex="-1" role="dialog" aria-labelledby="Misectoreliminar" aria-hidden="true">
        <div class="modal-dialog" role="document">
            @using (Html.BeginForm("Eliminar", "GruposCuarteles", new { cuar_id = ViewBag.cuar_id }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title col-sm-11 col-md-11 col-lg-11 col-xl-11">¿Desea Eliminar El Sector <label id="nombresector"></label> ?</h4>
                        <button type="button" class="close col-sm-1 col-md-1 col-lg-1 col-xl-1" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <!--Contenido del centro-->

                    @Html.Hidden("gc_id")

                    <div class="modal-footer">
                        @* <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>*@
                        <button type="submit" class="btn btn-primary">Eliminar</button>
                    </div>
                </div>
            }
        </div>
    </div>



    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script>
        $(document).ready(function () {

            $('#contenido_vista').appendTo('#contenido_general');
        });


        $(".addGrupos").on("click", function () {

            $("#ObjGruposCuarteles_ConJefe_id").attr("name", "ObjGruposCuarteles.ConJefe_id");

        });
        $(".sectoreliminar").on("click", function () {

            $("#gc_id").val($(this).attr("id"));
            var nom = $(this).attr("name");
            document.getElementById("nombresector").innerHTML = nom;
            //$("#nombresector").val($(this).attr("name"));
        });
    </script>